version: '3'
services:
  node-app:
    container_name: RESTAURANT_AGGREGATOR
    restart: always
    build: .
    ports:
      - '3001:3001'
    env_file:
      - ./.env
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    command: mongod --port 27018
    ports:
        - '27018:27018'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      restart: always
    volumes:
      - mongodb-vol:/data/db
  redis:
    image: redis
    command: --port 6380

volumes:
  mongodb-vol: